services:
  frontend:
    image: jupyter/scipy-notebook:2023-02-28
    ports:
      - "10001:8888"
    networks:
      - front-tier
      - back-tier

  backend:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: alina
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/data/db
    networks:
      - back-tier